[project]
name = "archivuelo"
version = "0.2"
dependencies = [
    "click",
    "peewee",
    "pymobiledevice3",
    "tqdm",
    "xxhash",
]
requires-python = ">=3.12"

[project.scripts]
archivuelo = "archivuelo.cli:archivuelo"